---
title: "Figure 1A"
author: "Richel J.C. Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{Figure 1A}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Goal of this vignette is to re-create figure 1C.

# Setup

```{r}
library(ggplot2)
library(huisweis)
```

# Constants


```{r}
n_species <- 3
n_resources <- 3
```

Half-saturation constants for resources:

```{r}
hsrs <- create_hsrs_1_a()
knitr::kable(hsrs)
```

Species resource contents:

```{r}
srcs <- create_srcs_1_a()
knitr::kable(srcs)
```

```{r}
supply_rates <- get_supply_rates()
print(supply_rates)
initial_resource_densities <- supply_rates
print(initial_resource_densities)
initial_species_densities <- create_init_spec_densities(n_species = n_species)
print(initial_species_densities)
max_growth_rates <- get_max_growth_rates(n_species = n_species)
mortality_rates <- get_mortality_rates(n_species = n_species)
print(mortality_rates)
turnover_rate <- get_turnover_rate()
print(turnover_rate)
t_max <- 100
print(t_max)
dt <- 0.01
print(dt)
```

```{r}
df <- run_sim(
  initial_species_densities = initial_species_densities,
  initial_resource_densities = initial_resource_densities,
  dt = dt,
  t_max = t_max,
  max_growth_rates = max_growth_rates,
  mortality_rates = mortality_rates,
  hsrs = hsrs,
  srcs = srcs,
  supply_rates = supply_rates,
  turnover_rate = turnover_rate
)
knitr::kable(head(df))
```


```{r}
df_long <- reshape2::melt(df, id = "t")
knitr::kable(head(df_long))
names(df_long)
```

```{r}
ggplot(data = df_long, aes(x = t, y = value, fill = variable)) + geom_line()
```