---
title: "Figure 1C"
author: "Richel J.C. Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Figure 1C}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Goal of this vignette is to re-create figure 1C.

# Setup

```{r}
library(huisweis)
```

# Constants


```{r}
n_species <- 6
n_resources <- 3
```

Half-saturation constants for resources:

```{r}
hsrs <- create_hsrs_1_c()
knitr::kable(hsrs)
```

Species resource contents:

```{r}
srcs <- create_srcs_1_c()
knitr::kable(srcs)
```

```{r}
supply_rates <- c(6, 10, 15)
print(supply_rates)
```

```{r}
species_densities <- create_init_spec_densities(n_species = n_species)
print(species_densities)
```

```{r}
max_growth_rates <- get_max_growth_rates(n_species = n_species)
print(max_growth_rates)
```

```{r}
resource_densities <- supply_rates
print(resource_densities)
```

```{r}
mortality_rates <- get_mortality_rates(n_species = n_species)
print(mortality_rates)
```

```{r}
turnover_rate <- get_turnover_rate()
print(turnover_rate)
```

